[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24" 

[profile.optimizations]
number = 200 

[profile.remappings]
"lib/account-abstraction/=" = "lib/account-abstraction/contracts/"
"openzeppelin/=" = "lib/openzeppelin-contracts/"

[rpc_endpoints] 
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }